# Generated by Django 3.1.4 on 2021-01-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_registration',
            name='host_password',
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='description',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
